image: python

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - echo "Test"
    - mkdir htmlcov
    - python -m pip install --upgrade pytest coverage
    - python -m compileall -f .
    # - python -m pytest -v
    # - python -m coverage run --source "./" --omit "./sampledbapi/test/*" -m pytest
    - python -m coverage report
    - python -m coverage html
  artifacts:
    paths:
      - htmlcov/

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - dpkg --add-architecture i386
    - apt-get update
    - apt-get install wget software-properties-common apt-transport-https ca-certificates -y
    - apt-get update
    - python -m pip install twine pyftpsync sphinx sphinx_rtd_theme
    - python setup.py install
    - python setup.py sdist bdist_wheel
    - twine upload dist/*
    - cd doc
    - sphinx-apidoc -o . ../sampledbapi -f -P -M -e
    - sphinx-build -b html . _build
    - cd ..
  artifacts:
    paths:
      - dist/
      - doc/_build/
  only:
    - tags
