image: python:latest

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - echo "Test"
    - mkdir htmlcov
    - python -m pip install --upgrade pytest coverage
    - python -m compileall -f .
    # - python -m pytest -v
    # - python -m coverage run --source "./" --omit "./sampledbapi/test/*" -m pytest
    # - python -m coverage report
    # - python -m coverage html
  artifacts:
    paths:
      - htmlcov/

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - apt-get update
    - apt-get install wget software-properties-common apt-transport-https ca-certificates -y
    - python -m pip install twine
    - python setup.py install
    - python setup.py sdist bdist_wheel
    - twine upload dist/*
  artifacts:
    paths:
      - dist/
    expire_in: 6 months
  only:
    - tags

pages:
  stage: deploy
  script:
    - python -m pip install sphinx sphinx_rtd_theme m2r2
    - python setup.py install
    - mkdir .public
    - cd doc
    - sphinx-apidoc -o . ../sampledbapi -f -P -M -e
    - sphinx-build -b html . _build
    - mv _build/* ../.public/
    - cd ..
    - mv .public public
  only:
    - tags
  artifacts:
    paths:
      - public
    expire_in: 1 hour
