image: python:latest

stages:
  - test
  - deploy

test:
  stage: test
  parallel:
    matrix:
      - IMAGE: ['python:3.7-slim', 'python:3.8-slim', 'python:3.9-slim', 'python:3.10-slim', 'python:3.11-slim']
  image: $IMAGE
  script:
    - mkdir htmlcov
    - mkdir mypycov
    - python -m pip install --upgrade pytest pytest-html coverage requests-mock mypy types-requests lxml
    - python -m compileall -f .
    - python -m pytest -v
    - python -m pytest --html=report.html --self-contained-html
    - python -m coverage run --source "./" --omit "./test/*",setup.py -m pytest
    - python -m coverage report
    - python -m coverage html
    - python -m mypy sampledbapi --html-report mypycov
  artifacts:
    paths:
      - report.html
      - htmlcov/
      - mypycov/
    expire_in: 1 month
    when: always

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - apt-get update
    - apt-get install wget software-properties-common apt-transport-https ca-certificates -y
    - python -m pip install twine
    - python setup.py install
    - python setup.py sdist bdist_wheel
    - twine upload dist/*
  artifacts:
    paths:
      - dist/
    expire_in: 6 months
  only:
    - tags

pages:
  stage: deploy
  script:
    - apt-get update
    - apt-get install pandoc -y
    - python -m pip install sphinx sphinx_rtd_theme IPython ipykernel nbsphinx m2r2
    - python setup.py install
    - mkdir .public
    - cd doc
    - sphinx-apidoc -o . ../sampledbapi -f -P -M -e
    - sphinx-build -b html . _build
    - mv _build/* ../.public/
    - cd ..
    - mv .public public
  only:
    - tags
  artifacts:
    paths:
      - public
    expire_in: 1 hour
